module ::= moduleclause ';' definitions | moduleclause WHERE '{' definitions '}' | INTERPRET script
definitions ::= definition | definition semicoli | definition semicoli definitions
definition ::= documentation | documentation definition | topdefinition | visibledefinition
topdefinition ::= import | infix | moduledefinition | publicdefinition
visibledefinition ::= PRIVATE publicdefinition | PROTECTED publicdefinition | PUBLIC publicdefinition | ABSTRACT datadef
publicdefinition ::= typedef | datadef | classdef | instdef | derivedef | localdef
classdef ::= CLASS ccontext EARROW CONID tyvar wheredef | CLASS ccontext wheredef
datadef ::= datainit wheredef
instdef ::= INSTANCE insthead wheredef
wheredef ::= | WHERE '{' '}' | WHERE '{' localdefs '}'
localdefs ::= dplocaldef | dplocaldef semicoli | dplocaldef semicoli localdefs
dplocaldef ::= documentation | documentation dplocaldef | plocaldef
plocaldef ::= localdef | PRIVATE localdef | PROTECTED localdef | PUBLIC localdef
localdef ::= annotation | nativedef | fundef
script ::= expr
appex ::= unex | appex unex
lambdabody ::= lambda | ARROW expr
getfield ::= VARID GETS expr | VARID '=' expr | VARID
getfields ::= getfield | getfield ',' getfields | getfield ','
dodefs ::= lcqual | lcqual semicoli | lcqual semicoli dodefs
lcqual ::= gqual | expr '=' expr | LET '{' letdefs '}'
lcquals ::= lcqual | lcqual ',' lcquals | lcqual ','
exprSS ::= expr | expr ';' exprSS | expr ';'
exprSC ::= expr | expr ',' exprSC | expr ','
field ::= varid '=' expr | varid
fields ::= field | field ',' fields | field ','
term ::= qvarid | literal | '_' | qconid | qconid '{' '}' | qconid '{' fields '}' | '(' ')' | '(' commata ')' | '(' unop ')' | '(' operator ')' | '(' '-' ')' | '(' operator expr ')' | '(' binex operator ')' | '(' binex '-' ')' | '(' expr ',' exprSC ')' | '(' expr ';' exprSS ')' | '(' expr ')' | '[' ']' | '[' exprSC ']' | '[' exprSC DOTDOT ']' | '[' exprSC DOTDOT expr ']' | '[' expr '|' lcquals ']'
primary ::= term | DO '{' dodefs '}' | primary '.' VARID | primary '.' operator | primary '.' unop | qualifiers '{' VARID '?' '}' | qualifiers '{' VARID '=' '}' | qualifiers '{' VARID GETS '}' | qualifiers '{' getfields '}' | primary '.' '{' VARID '?' '}' | primary '.' '{' VARID '=' '}' | primary '.' '{' VARID GETS '}' | primary '.' '{' getfields '}' | primary '.' '[' expr ']'
unex ::= primary | unop unex
apats ::= unex | unex apats
lambda ::= '\' apats lambdabody
wherelet ::= WHERE '{' '}' | WHERE '{' letdefs '}'
gqual ::= expr | expr GETS expr
gquals ::= gqual | gqual ',' gquals | gqual ','
guard ::= '|' gquals aeq expr
guards ::= guard | guard guards
funhead ::= binex
fundef ::= funhead '=' expr | funhead guards | fundef wherelet
letdef ::= annotation | fundef
letdefs ::= letdef | letdef semicoli | letdef semicoli letdefs
calts ::= calt | calt ';' calts | calt ';'
topex ::= IF expr thenx expr elsex expr | CASE expr OF '{' calts '}' | LET '{' letdefs '}' IN expr | lambda | appex
binex ::= binex SOMEOP binex | binex '-' binex | '-' topex | topex
expr ::= binex DCOLON sigma | binex
pattern ::= expr
calt ::= pattern aeq expr | pattern guards | calt wherelet
aeq ::= ARROW | '='
import ::= IMPORT modulename importliste | IMPORT modulename VARID CONID importliste | IMPORT modulename CONID importliste
importliste ::= | varid '(' importspecs ')' | '(' ')' | '(' importspecs ')' | PUBLIC importliste
importspecs ::= importspec | importspec ',' | importspec ',' importspecs
importspec ::= importitem | importitem alias | PUBLIC importspec
importitem ::= qvarid | CONID '(' memspecs ')' | CONID '(' ')' | qconid | operator | unop
memspecs ::= memspec | memspec ',' | memspec ',' memspecs
memspec ::= alias | alias alias | PUBLIC memspec
alias ::= VARID | CONID | operator
annotation ::= annoitems DCOLON sigma
annoitems ::= annoitem | annoitem ',' annoitems
nativedef ::= PURE impurenativedef | impurenativedef
impurenativedef ::= NATIVE methodspec DCOLON sigexs
methodspec ::= fitem jitem gargs | fitem jitem | fitem gargs | fitem
fitem ::= annoitem | unop | '-' | operator
annoitem ::= varid | '(' operator ')' | '(' unop ')' | '(' '-' ')'
datainit ::= DATA CONID '=' nativepur nativespec | DATA CONID dvars '=' nativepur nativespec | DATA CONID dvars '=' dalts | DATA CONID '=' dalts | NEWTYPE CONID dvars '=' dalt | NEWTYPE CONID '=' dalt
dalts ::= dalt | dalt '|' dalts
dalt ::= visdalt | visdalt DOCUMENTATION | DOCUMENTATION visdalt
visdalt ::= strictdalt | PUBLIC strictdalt | PRIVATE strictdalt | PROTECTED strictdalt
strictdalt ::= '!' simpledalt | '?' simpledalt | simpledalt
simpledalt ::= CONID | CONID '{' conflds '}' | CONID contypes
conflds ::= confld | confld ',' | confld DOCUMENTATION | confld ',' conflds | confld DOCUMENTATION conflds
confld ::= fldids DCOLON sigma | docs fldids DCOLON sigma
sigexs ::= sigex | sigex '|' sigexs
sigex ::= sigma THROWS tauSC | sigma
typedef ::= TYPE CONID '=' sigma | TYPE CONID dvars '=' sigma
sigma ::= forall | rho
derivedef ::= DERIVE insthead
insthead ::= icontext EARROW tyname simpletype | icontext
icontext ::= sicontext | '(' sicontexts ')'
sicontexts ::= sicontext | sicontext ',' | sicontext ',' sicontexts
sicontext ::= qconid simpletype
contypes ::= simpletypes
nativespec ::= nativename | nativename gargs
gargs ::= '{' tauSC '}' | '{' '}'
moduledefinition ::= NATIVE PACKAGE typeclause interfaces wheretokens
interfaces ::= | CLASS tauSC
typeclause ::= | TYPE tau
rhofun ::= tapp | tapp ARROW rhofun
tauSB ::= tau | tau '|' tauSB
tauSC ::= tau | tau ',' tauSC
tau ::= tapp | forall | tapp ARROW tau
simpletype ::= tyvar | tyname | '(' tau ')' | '(' tau ',' tauSC ')' | '(' tau '|' tauSB ')' | '[' tau ']'
simpletypes ::= simpletype | simpletype simpletypes
tapp ::= simpletypes
rho ::= tapp EARROW rhofun | rhofun
forall ::= FORALL boundvars mbdot rho
boundvars ::= boundvar | boundvar boundvars
boundvar ::= VARID
ccontext ::= scontext | '(' scontexts ')'
tyname ::= qconid | '[' ']' | '(' ')' | '(' commata ')' | '(' ARROW ')'
commata ::= ',' | ',' commata
moduleclause ::= docs PACKAGE modulename | PACKAGE modulename | docs PROTECTED PACKAGE modulename | PROTECTED PACKAGE modulename | moduleclause words '(' qvarids ')'
docs ::= DOCUMENTATION | DOCUMENTATION docs | DOCUMENTATION semicoli docs
documentation ::= DOCUMENTATION
dvars ::= tyvar | tyvar dvars
elsex ::= ';' ELSE | ELSE
infix ::= fixity operators
fixity ::= INFIX INTCONST | INFIXL INTCONST | INFIXR INTCONST
fldids ::= fldid | fldid ',' fldids
fldid ::= strictfldid | PUBLIC strictfldid | PRIVATE strictfldid
jitem ::= nativename | operator | unop
wheretokens ::= WHERE '{' jtokens '}' | WHERE '{' '}'
jtokens ::= jtoken | jtoken jtokens | '{' jtokens '}' | '{' jtokens '}' jtokens | '{' '}' | '{' '}' jtokens
jtoken ::= VARID | CONID | QVARID | QCONID | QUALIFIER | DOCUMENTATION | PACKAGE | IMPORT | INFIX | INFIXR | INFIXL | NATIVE | DATA | WHERE | CLASS | INSTANCE | ABSTRACT | TYPE | TRUE | FALSE | IF | THEN | ELSE | CASE | OF | DERIVE | LET | IN | DO | FORALL | PRIVATE | PROTECTED | PUBLIC | PURE | THROWS | MUTABLE | INTCONST | STRCONST | LONGCONST | FLTCONST | DBLCONST | CHRCONST | ARROW | DCOLON | GETS | EARROW | DOTDOT | SOMEOP | INTERPRET | ',' | '|' | '[' | ']' | '(' | ')' | '.' | '?' | '-' | ';' | '!' | '=' | '\'
scontexts ::= scontext | scontext ',' | scontext ',' scontexts
scontext ::= qconid tyvar
tyvar ::= VARID | '(' VARID DCOLON kind ')'
simplekind ::= SOMEOP | VARID | '(' kind ')'
kind ::= simplekind ARROW kind | simplekind
literal ::= TRUE | FALSE | CHRCONST | STRCONST | INTCONST | BIGCONST | LONGCONST | FLTCONST | DBLCONST | REGEXP
mbdot ::= '.' | SOMEOP
modulename ::= modulename1
modulename1 ::= CONID | varidkw '.' modulename1 | QUALIFIER modulename1
nativename ::= rawnativename
nativepur ::= PURE NATIVE | MUTABLE NATIVE | NATIVE
operators ::= opstring | opstring operators
opstring ::= operator | VARID | '-'
qvarids ::= qvarop | qvarop ',' qvarids
qvarop ::= QUALIFIER QUALIFIER varop | QUALIFIER varop | varop | operator
operator ::= SOMEOP
strictfldid ::= plainfldid | '!' plainfldid | '?' plainfldid
plainfldid ::= varid
qconid ::= QUALIFIER QUALIFIER CONID | QUALIFIER CONID | CONID
qualifiers ::= QUALIFIER | QUALIFIER QUALIFIER
qvarid ::= QUALIFIER QUALIFIER varop | QUALIFIER varop | VARID
rawnativename ::= VARID | CONID | PACKAGE | VARID '.' rawnativename | PACKAGE '.' rawnativename | QUALIFIER rawnativename | STRCONST
semicoli ::= ';' | ';' semicoli
thenx ::= ';' THEN | THEN
varop ::= VARID | unop
unop ::= '!' | '?'
varid ::= VARID
varidkw ::= VARID | DATA | TYPE | NATIVE | PURE | PACKAGE | IMPORT
words ::= word | word words
word ::= VARID
GETS ::= '<-' | '←'
DCOLON ::= '::' | '∷'
LowercaseLetter ::= '«any character in Unicode category: Letter, Lowercase»'
ARROW ::= '->' | '→'
WHERE ::= 'where'
Letter ::= '«any character in Unicode category: Letter»'
VARID ::= (LowercaseLetter | '_') (Letter | '_' | "'")*
