ARROW: '->'  | '→' ;
GETS:  '<-'  | '←' ;
DCOLON: '::' | '∷' ;
WHERE: 'where' ;
QUALIFIER: CONID '.' ;
VARID: (LowercaseLetter | '_') (Letter | '_' | "'")* ;
Letter: ('«any character in Unicode category: Letter»');
LowercaseLetter: ('«any character in Unicode category: Letter, Lowercase»');