ARROW: '->'
EARROW: '=>'
GETS:  '<-'
DCOLON: '::'
DOTDOT: '..'
INSTANCE: 'instance'
CLASS: 'class'
DATA: 'data'
TYPE: 'type'
NEWTYPE: 'newtype'
PURE: 'pure'
MUTABLE: 'mutable'
IMPORT: 'import'
WHERE: 'where'
THEN: 'then'
ELSE: 'else'
IF: 'if'
CASE: 'case'
OF: 'of'
LET: 'let'
IN: 'in'
DO: 'do'
NATIVE: 'native'
PACKAGE: 'module'
CASE: 'case'
QUALIFIER: CONID '.' 
VARID: (LowercaseLetter | '_') (Letter | Digit | '_' | "'")*
CONID: UppercaseLetter (Letter | Digit | '_' | "'")* 
Letter: '«any character in Unicode category: Letter»'
LowercaseLetter: '«any character in Unicode categories Letter and not Uppercase»'
UppercaseLetter: '«any character in Unicode categories Letter and Uppercase»'
Digit: [0-9]
STRCONST: '"' ([^"]|'\"') '"'
